os: linux
dist: bionic

notifications:
  email: false
cache: pip
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - graphviz
      - pandoc
jobs:
  fast_finish: true
  include:
    - if: branch = master AND type = push
      python: "3.7"
      script: travis_wait 50 tools/deploy_translated_documentation.sh
      git:
        depth: false
    - if: branch = master AND type = push
      python: "3.7"
      script: travis_wait 50 tools/deploy_translatable_strings.sh
      git:
        depth: false
